import json

pairs = [
  ("Bilirubine Indirecte", "BILIRUBINE INDIRECTE/NON CONJUGUEE", "Same test: indirect/unconjugated bilirubin, CDL short name, DYN includes both terms"),
  ("C Telopeptides", "TELEPEPTIDE-C", "Same test: C-telopeptide bone resorption marker, different name order and accents"),
  ("Calcium Urine 24 Heures (Urine 24h)", "CALCIUM URINES DE 24 HEURES", "Same test: 24-hour urine calcium"),
  ("Calprotectine", "CALPROTECTINE FECALE", "Same test: fecal calprotectin, CDL name is abbreviated"),
  ("Chaines Legeres Kappa Lambda Libre", "CHAINES LEGERES LIBRES", "Same test: free kappa and lambda light chains combined"),
  ("Chlorure Urine 24 Heures (Urine 24h)", "CHLORURES - URINES DE 24 HEURES", "Same test: 24-hour urine chloride"),
  ("Cortisol AM PM", "CORTISOL (MATIN ET APRES-MIDI)", "Same test: morning and afternoon cortisol measurement"),
  ("Cortisol Urine 24 Heures (Urine 24h)", "CORTISOL LIBRE - URINES DE 24 HEURES", "Same test: 24-hour urinary free cortisol"),
  ("Cystatin C", "CYSTATINE C", "Same test: cystatin C renal function marker, English vs French spelling"),
  ("Dheas", "DHEAS (SULFATE DE DESHYDROEPIANDROSTERONE)", "Same test: DHEA-sulfate, CDL canonical is abbreviated"),
  ("Digoxin", "DIGOXINE", "Same drug level test: digoxin, English vs French name"),
  ("Electrolytes Urine 24 Heures (Urine 24h)", "ELECTROLYTES - URINES DE 24 HEURES", "Same test: 24-hour urine electrolytes panel"),
  ("Epstein Barr VCA IGG", "ANTICORPS ANTI-VIRUS EPSTEIN-BARR DE TYPE IgG", "Same test: Epstein-Barr virus VCA IgG antibody"),
  ("Epstein Barr VCA IGM", "ANTICORPS ANTI-VIRUS EPSTEIN-BARR DE TYPE IgM", "Same test: Epstein-Barr virus VCA IgM antibody"),
  ("Glucose 6 PO4 DH Quantitatif Sang Entier (Sang Entier)", "G6PD (GLUCOSE-6-PHOSPHATE DESHYDROGENASE)", "Same test: glucose-6-phosphate dehydrogenase in whole blood"),
  ("Glucose Aleatoire", "GLUCOSE AU HASARD", "Same test: random glucose, aleatoire = au hasard"),
  ("Glucose Test Tolerance 2 Heures", "GLUCOSE - HYPERGLYCEMIE ORALE 75g NON-GESTATIONNEL (2 HEURES)", "Same test: 2-hour oral glucose tolerance test non-gestational"),
  ("Harmony", "HARMONY (DEPISTAGE PRENATAL NON INVASIF)", "Same test: Harmony prenatal cell-free DNA screening"),
  ("Hepatite A IGG", "ANTICORPS TOTAUX ANTI-HEPATITE A (IgG)", "Same test: hepatitis A total IgG antibodies"),
  ("Hepatite A IGM", "ANTICORPS ANTI-HEPATITE A DE TYPE IgM", "Same test: hepatitis A IgM antibody for acute infection"),
  ("Hepatite B Anticorps Core Total", "ANTICORPS ANTI-HBc (TOTAL)", "Same test: total anti-HBc hepatitis B core antibody"),
  ("Hepatite B Anticorps Surface", "ANTI-HBs", "Same test: hepatitis B surface antibody anti-HBs"),
  ("Hepatite B Charge Virale", "HEPATITE B - ADN VIRAL", "Same test: hepatitis B viral load / DNA quantification"),
  ("Hepatite B E Anticorps", "ANTICORPS ANTI-HBe", "Same test: hepatitis B e antibody anti-HBe"),
  ("Hepatite C Charge Virale", "HEPATITE C (ANALYSE QUANTITATIVE) - PCR", "Same test: hepatitis C viral load by quantitative PCR"),
  ("Herpes Simplex Virus 1 2 ADN PCR", "HERPES - DETECTION PAR PCR (ECOUVILLON)", "Same test: herpes simplex virus 1 and 2 PCR detection from swab"),
  ("Holter 24 Heures", "HOLTER (24 HRS) - ECG EN CONTINU", "Same test: 24-hour Holter continuous ECG monitoring"),
  ("Holter 48 Heures", "HOLTER (48 HRS) - ECG EN CONTINU", "Same test: 48-hour Holter continuous ECG monitoring"),
  ("IGF 1", "IGF-1 (SOMATOEDINE C)", "Same test: insulin-like growth factor 1 somatomedin C"),
  ("IGG Sous Classe", "SOUS-CLASSES D IMMUNOGLOBULINE IgG", "Same test: IgG subclass quantification"),
  ("Lamotrigine", "LAMOTRIGINE (LAMICTAL)", "Same drug level test: lamotrigine, DYN adds brand name Lamictal"),
  ("LP A", "LIPOPROTEINE A - Lp(a)", "Same test: lipoprotein(a), abbreviated vs full name"),
  ("Microalbuminurie Aleatoire", "MICROALBUMINE: RATIO ALBUMINE/CREATININE", "Same test: spot urine microalbumin random collection"),
  ("Microalbuminurie Urine 24 Heures (Urine 24h)", "MICROALBUMINE - URINES DE 24 HEURES", "Same test: 24-hour urine microalbumin"),
  ("Monotest (MONO)", "MONONUCLEOSE - TEST DE DEPISTAGE", "Same test: mononucleosis screening test"),
  ("Oreillons IGG", "ANTICORPS IgG ANTI-VIRUS DES OREILLONS", "Same test: mumps IgG antibody"),
  ("Oreillons IGM", "ANTICORPS IgM ANTI-VIRUS DES OREILLONS", "Same test: mumps IgM antibody"),
  ("Oxalate Urine 24 Heures (Urine 24h)", "OXALATES - URINES DE 24 HEURES", "Same test: 24-hour urine oxalates"),
  ("Oxyures", "OXYURES (SPATULE ADHESIVE)", "Same test: pinworm detection, DYN specifies adhesive tape method"),
  ("Phenytoine", "DILANTIN (PHENYTOINE)", "Same drug level test: phenytoin Dilantin, generic vs brand name first"),
  ("Phosphate Urine 24 Heures (Urine 24h)", "PHOSPHORE - URINES DE 24 HEURES", "Same test: 24-hour urine phosphate/phosphorus"),
  ("Proteines Urine 24 Heures (Urine 24h)", "PROTEINES - URINES DE 24 HEURES", "Same test: 24-hour urine total protein"),
  ("Rage Anticorps", "ANTICORPS ANTI-RABIQUES (RAGE)", "Same test: rabies antibody titre"),
  ("Recherche Danticorps", "RECHERCHE D ANTICORPS (TEST DE COOMBS INDIRECT)", "Same test: antibody screen indirect Coombs test"),
  ("Reticulocytes", "RETICULOCYTES (NUMERATION)", "Same test: reticulocyte count"),
  ("Rougeole IGG", "ANTICORPS IgG ANTI-VIRUS DE LA ROUGEOLE", "Same test: measles rubeola IgG antibody"),
  ("Rougeole IGM", "ANTICORPS IgM ANTI-VIRUS DE LA ROUGEOLE", "Same test: measles rubeola IgM antibody"),
  ("Rubeole IGM", "ANTICORPS IgM ANTI-VIRUS DE LA RUBEOLE", "Same test: rubella IgM antibody"),
  ("Sodium Urine 24 Heures (Urine 24h)", "SODIUM URINES DE 24 HEURES", "Same test: 24-hour urine sodium"),
  ("Syphilis EIA", "SYPHILIS CMIA (DEPISTAGE)", "Same test: syphilis serological screening, EIA and CMIA are equivalent immunoassay methods"),
  ("T3 Totale", "T3 TOTALE (TRIIODOTHYRONINE)", "Same test: total triiodothyronine T3"),
  ("Tacrolimus Fk506 Prograf", "TACROLIMUS", "Same drug level test: tacrolimus FK506/Prograf, CDL includes brand names"),
  ("Toxoplasmose IGG", "TOXOPLASMOSE ANTICORPS DE TYPE IgG", "Same test: toxoplasma IgG antibody"),
  ("Toxoplasmose IGM", "TOXOPLASMOSE ANTICORPS DE TYPE IgM", "Same test: toxoplasma IgM antibody"),
  ("Trichomonas PCR Urine (Urine)", "TRICHOMONAS VAGINALIS URINE - DEPISTAGE PAR TAAN", "Same test: Trichomonas vaginalis PCR/TAAN from urine"),
  ("Trichomonas Vaginalis PCR (Vaginal)", "TRICHOMONAS VAGINALIS ECOUVILLON - DEPISTAGE PAR TAAN", "Same test: Trichomonas vaginalis PCR from swab/vaginal specimen"),
  ("TSH Anticorps Anti Recepteur", "ANTICORPS ANTI-RECEPTEURS DE LA THYREOSTIMULINE (TBII)", "Same test: TSH receptor antibodies TBII/TRAb"),
  ("Uree Urine 24 Heures BUN (Urine 24h)", "UREE - URINES DE 24 HEURES", "Same test: 24-hour urine urea"),
  ("VIH Virus Immunodeficience Humaine Charge Virale", "CHARGE VIRALE (VIH)", "Same test: HIV viral load"),
  ("Varicelle IGG", "ANTICORPS IgG ANTI-VARICELLE", "Same test: varicella-zoster virus IgG antibody"),
  ("Varicelle IGM", "ANTICORPS IgM ANTI-VARICELLE", "Same test: varicella-zoster virus IgM antibody"),
  ("Anti Endomysiaux Anticorps IGA", "ANTICORPS ANTI-ENDOMYSIUM", "Same test: anti-endomysial antibody IgA for celiac disease"),
  ("Anti GAD Auto Anticorps", "ANTICORPS ANTI-GLUTAMATE DECARBOXYLASE", "Same test: anti-GAD glutamate decarboxylase autoantibody"),
  ("Anti TPO", "ANTICORPS ANTI-MICROSOMES THYROIDIENS", "Same test: anti-thyroid peroxidase anti-TPO equals anti-thyroid microsomal antibodies"),
  ("Chlamydia Urine (Urine)", "CHLAMYDIA URINE - DEPISTAGE PAR TAAN", "Same test: chlamydia urine TAAN/PCR screening"),
  ("Chlamydia PCR", "CHLAMYDIA ECOUVILLON - DEPISTAGE PAR TAAN", "Same test: chlamydia swab PCR/TAAN screening"),
  ("Gonorrhee PCR Urine (Urine)", "NEISSERIA GONORRHOEAE - DEPISTAGE PAR TAAN URINE", "Same test: Neisseria gonorrhoeae urine PCR/TAAN"),
  ("Gonorrhee PCR", "NEISSERIA GONORRHOEAE - DEPISTAGE PAR TAAN ECOUVILLONNAGE", "Same test: Neisseria gonorrhoeae swab PCR/TAAN"),
  ("Sang Dans Selles Immunologique Quantitatif (Selles)", "FIT (TEST IMMUNOCHIMIQUE FECAL)", "Same test: fecal immunochemical test FIT for occult blood"),
  ("HFE Genotype", "MUTATION GENIQUE HEMOCHROMATOSE (C282Y + H63D)", "Same test: HFE gene mutations C282Y and H63D for hereditary hemochromatosis"),
  ("HLA Celiac", "TYPAGE HLA DQ2/DQ8", "Same test: HLA DQ2/DQ8 typing for celiac disease susceptibility"),
  ("Immunoglobuline", "IMMUNOGLOBULINES (ANALYSE QUANTITATIVE)", "Same test: quantitative immunoglobulins panel IgG IgA IgM"),
  ("PAP Thinpreptm Test", "CYTOLOGIE: TEST DE PAPANICOLAOU ThinPrep (PAP TEST LIQUIDE)", "Same test: ThinPrep liquid-based Pap test"),
  ("PAP Frottis Traditionnel", "CYTOLOGIE: TEST DE PAPANICOLAOU (SUR LAME)", "Same test: traditional Pap smear on slide"),
  ("Test PAP Thin Prep HPV DNA", "CYTOLOGIE: ThinPrep + DEPISTAGE VPH EN COMBO", "Same test: ThinPrep Pap + HPV co-testing"),
  ("Lyme Maladie IGG OU IGM Lymg Lymm", "MALADIE DE LYME (ANTICORPS ANTI-BORRELIA BURGDORFERI)", "Same test: Lyme disease Borrelia burgdorferi antibody screening IgG/IgM"),
  ("Estrone", "OESTRONE (ESTRONE)", "Same test: estrone E1 steroid hormone, English vs French/alternative spelling"),
  ("Cuivre Globules Rouges (Globules Rouges)", "CUIVRE SANG ENTIER", "Same test: copper in red blood cells/whole blood, both measure cellular copper"),
  ("C Peptide", "PEPTIDE C A JEUN", "Same test: C-peptide, clinically measured fasting, DYN specifies fasting requirement explicitly"),
  ("Culture Cervicale (Cervical)", "CULTURE: COL UTERIN", "Same test: cervical culture (col uterin = cervix in French)"),
  ("Culture Crachat (Crachat)", "CULTURE: EXPECTORATIONS", "Same test: sputum culture (crachat = expectoration in French)"),
  ("Culture Vaginale Culture Traditionnelle (Vaginal)", "CULTURE: VAGIN", "Same test: traditional vaginal culture"),
  ("Culture Urethrale", "CULTURE: URETRE", "Same test: urethral culture"),
  ("Culture Fongique Peau Cheveux Ongles (Cheveux)", "CULTURE: CHAMPIGNONS", "Same test: fungal culture of skin/hair/nails"),
  ("Maladie Coeliaque", "PROFIL MALADIE COELIAQUE COMPLET (IgA TOTALES, ANTI-TRANSGLUTAMINASE IgA, ANTI-GLIADINE IgG ET IgA)", "Same test: comprehensive celiac disease antibody panel"),
  ("PT PTT", "INR + PTT (TEMPS DE CEPHALINE ACTIVEE)", "Same test: prothrombin time PT/INR combined with activated partial thromboplastin time PTT"),
  ("Glucose AC", "GLUCOSE A JEUN", "Same test: fasting glucose (AC = avant les repas/a jeun = fasting)"),
  ("Glucose AC PC 1H", "GLUCOSE PC (1HR-50g)", "Same test: 1-hour 50g gestational glucose challenge test"),
  ("Glucose AC PC 2H", "GLUCOSE PC (2HR-75g)", "Same test: 2-hour 75g gestational oral glucose tolerance test"),
]

# Now use the ACTUAL canonical values from the files
with open("D:/lab-price/prisma/cdl_only.json", encoding="utf-8") as f:
    cdl = json.load(f)
with open("D:/lab-price/prisma/dyn_only.json", encoding="utf-8") as f:
    dyn = json.load(f)

cdl_map = {item["canonical"]: item for item in cdl}
dyn_map = {item["canonical"]: item for item in dyn}

print("CDL canonicals with accents:")
for k in cdl_map:
    if any(c in k for c in ["é","è","ê","ë","à","â","î","ô","û","ù","ï","ü","ç","É","È","Ê","Ë","À","Â","Î","Ô","Û"]):
        print(" ", repr(k))
