/**
 * seed-dynacare-profiles.ts
 * Seeds Dynacare ProfileTests from prisma/dynacare-profiles.json as BundleDeals.
 *
 * Rules:
 * 1. Deletes all existing DYN bundle_deals (sourceLabCode = "DYNACARE") before re-inserting.
 * 2. Inserts each profile as a BundleDeal with sourceLabCode = "DYNACARE".
 * 3. testMappingIds = [] (empty — profiles are catalog bundles without mapped individual tests).
 */

import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../app/generated/prisma/index.js";
import * as fs from "fs";
import * as path from "path";

const connectionString = process.env.DATABASE_URL!;
const prisma = new PrismaClient({ adapter: new PrismaPg({ connectionString }) });

type DynProfile = {
  code: string;
  name: string;
  description: string;
  price: number;
  turnaroundTime: string;
  tubeType: string;
  category: string;
  icon: string;
};

async function main() {
  console.log("🔄  Starting Dynacare profiles seed…\n");

  const dataPath = path.join(__dirname, "dynacare-profiles.json");
  const profiles: DynProfile[] = JSON.parse(fs.readFileSync(dataPath, "utf8"));
  console.log(`📋  Loaded ${profiles.length} Dynacare profiles from JSON\n`);

  // Delete existing DYN bundle_deals
  const { count: deleted } = await prisma.bundleDeal.deleteMany({
    where: { sourceLabCode: "DYNACARE" },
  });
  console.log(`🗑️   Deleted ${deleted} existing DYN bundle deals\n`);

  // Insert profiles as bundle_deals
  let created = 0;
  let errors = 0;

  for (let i = 0; i < profiles.length; i++) {
    const p = profiles[i];
    try {
      await prisma.bundleDeal.create({
        data: {
          dealName: p.name,
          description: p.description,
          category: p.category,
          icon: p.icon,
          customRate: p.price,
          popular: false,
          testMappingIds: [],
          isActive: true,
          sortOrder: i,
          sourceLabCode: "DYNACARE",
          profileCode: p.code,
          profilePrice: p.price,
          isAutoGenerated: false,
        },
      });
      created++;
    } catch (err) {
      console.error(`  ❌ Failed "${p.name}":`, (err as Error).message);
      errors++;
    }
  }

  const total = await prisma.bundleDeal.count({ where: { sourceLabCode: "DYNACARE" } });

  console.log(`
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✅  Dynacare profiles seed complete!

  Input profiles:       ${profiles.length}
  Created:              ${created}
  Errors / skipped:     ${errors}

  DB — DYN bundle_deals: ${total}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);
}

main()
  .catch((err) => {
    console.error("Fatal error:", err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
